/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as AdminUtentiRouteImport } from './routes/admin.utenti'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminLogEmailRouteImport } from './routes/admin.log-email'
import { Route as AdminConsoleRouteImport } from './routes/admin.console'
import { Route as AppSpesaRouteImport } from './routes/_app/spesa'
import { Route as AppRicetteRouteImport } from './routes/_app/ricette'
import { Route as AppPianoRouteImport } from './routes/_app/piano'
import { Route as AppImpostazioniRouteImport } from './routes/_app/impostazioni'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppDispensaRouteImport } from './routes/_app/dispensa'
import { Route as AppSpesaStoricoRouteImport } from './routes/_app/spesa.storico'
import { Route as AppRicetteNuovaRouteImport } from './routes/_app/ricette.nuova'
import { Route as AppImpostazioniSicurezzaRouteImport } from './routes/_app/impostazioni.sicurezza'
import { Route as AppImpostazioniScadenzeRouteImport } from './routes/_app/impostazioni.scadenze'
import { Route as AppImpostazioniProfiloRouteImport } from './routes/_app/impostazioni.profilo'
import { Route as AppImpostazioniPreferenzeRouteImport } from './routes/_app/impostazioni.preferenze'
import { Route as AppImpostazioniNotificheRouteImport } from './routes/_app/impostazioni.notifiche'
import { Route as AppImpostazioniCasaRouteImport } from './routes/_app/impostazioni.casa'
import { Route as AppDispensaAggiungiRouteImport } from './routes/_app/dispensa.aggiungi'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksDailyNotificationsRouteImport } from './routes/api/public/hooks/daily-notifications'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUtentiRoute = AdminUtentiRouteImport.update({
  id: '/utenti',
  path: '/utenti',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogEmailRoute = AdminLogEmailRouteImport.update({
  id: '/log-email',
  path: '/log-email',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConsoleRoute = AdminConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AdminRoute,
} as any)
const AppSpesaRoute = AppSpesaRouteImport.update({
  id: '/spesa',
  path: '/spesa',
  getParentRoute: () => AppRoute,
} as any)
const AppRicetteRoute = AppRicetteRouteImport.update({
  id: '/ricette',
  path: '/ricette',
  getParentRoute: () => AppRoute,
} as any)
const AppPianoRoute = AppPianoRouteImport.update({
  id: '/piano',
  path: '/piano',
  getParentRoute: () => AppRoute,
} as any)
const AppImpostazioniRoute = AppImpostazioniRouteImport.update({
  id: '/impostazioni',
  path: '/impostazioni',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppDispensaRoute = AppDispensaRouteImport.update({
  id: '/dispensa',
  path: '/dispensa',
  getParentRoute: () => AppRoute,
} as any)
const AppSpesaStoricoRoute = AppSpesaStoricoRouteImport.update({
  id: '/storico',
  path: '/storico',
  getParentRoute: () => AppSpesaRoute,
} as any)
const AppRicetteNuovaRoute = AppRicetteNuovaRouteImport.update({
  id: '/nuova',
  path: '/nuova',
  getParentRoute: () => AppRicetteRoute,
} as any)
const AppImpostazioniSicurezzaRoute =
  AppImpostazioniSicurezzaRouteImport.update({
    id: '/sicurezza',
    path: '/sicurezza',
    getParentRoute: () => AppImpostazioniRoute,
  } as any)
const AppImpostazioniScadenzeRoute = AppImpostazioniScadenzeRouteImport.update({
  id: '/scadenze',
  path: '/scadenze',
  getParentRoute: () => AppImpostazioniRoute,
} as any)
const AppImpostazioniProfiloRoute = AppImpostazioniProfiloRouteImport.update({
  id: '/profilo',
  path: '/profilo',
  getParentRoute: () => AppImpostazioniRoute,
} as any)
const AppImpostazioniPreferenzeRoute =
  AppImpostazioniPreferenzeRouteImport.update({
    id: '/preferenze',
    path: '/preferenze',
    getParentRoute: () => AppImpostazioniRoute,
  } as any)
const AppImpostazioniNotificheRoute =
  AppImpostazioniNotificheRouteImport.update({
    id: '/notifiche',
    path: '/notifiche',
    getParentRoute: () => AppImpostazioniRoute,
  } as any)
const AppImpostazioniCasaRoute = AppImpostazioniCasaRouteImport.update({
  id: '/casa',
  path: '/casa',
  getParentRoute: () => AppImpostazioniRoute,
} as any)
const AppDispensaAggiungiRoute = AppDispensaAggiungiRouteImport.update({
  id: '/aggiungi',
  path: '/aggiungi',
  getParentRoute: () => AppDispensaRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDailyNotificationsRoute =
  ApiPublicHooksDailyNotificationsRouteImport.update({
    id: '/api/public/hooks/daily-notifications',
    path: '/api/public/hooks/daily-notifications',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dispensa': typeof AppDispensaRouteWithChildren
  '/home': typeof AppHomeRoute
  '/impostazioni': typeof AppImpostazioniRouteWithChildren
  '/piano': typeof AppPianoRoute
  '/ricette': typeof AppRicetteRouteWithChildren
  '/spesa': typeof AppSpesaRouteWithChildren
  '/admin/console': typeof AdminConsoleRoute
  '/admin/log-email': typeof AdminLogEmailRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/utenti': typeof AdminUtentiRoute
  '/join/$code': typeof JoinCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/dispensa/aggiungi': typeof AppDispensaAggiungiRoute
  '/impostazioni/casa': typeof AppImpostazioniCasaRoute
  '/impostazioni/notifiche': typeof AppImpostazioniNotificheRoute
  '/impostazioni/preferenze': typeof AppImpostazioniPreferenzeRoute
  '/impostazioni/profilo': typeof AppImpostazioniProfiloRoute
  '/impostazioni/scadenze': typeof AppImpostazioniScadenzeRoute
  '/impostazioni/sicurezza': typeof AppImpostazioniSicurezzaRoute
  '/ricette/nuova': typeof AppRicetteNuovaRoute
  '/spesa/storico': typeof AppSpesaStoricoRoute
  '/api/public/hooks/daily-notifications': typeof ApiPublicHooksDailyNotificationsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dispensa': typeof AppDispensaRouteWithChildren
  '/home': typeof AppHomeRoute
  '/impostazioni': typeof AppImpostazioniRouteWithChildren
  '/piano': typeof AppPianoRoute
  '/ricette': typeof AppRicetteRouteWithChildren
  '/spesa': typeof AppSpesaRouteWithChildren
  '/admin/console': typeof AdminConsoleRoute
  '/admin/log-email': typeof AdminLogEmailRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/utenti': typeof AdminUtentiRoute
  '/join/$code': typeof JoinCodeRoute
  '/admin': typeof AdminIndexRoute
  '/dispensa/aggiungi': typeof AppDispensaAggiungiRoute
  '/impostazioni/casa': typeof AppImpostazioniCasaRoute
  '/impostazioni/notifiche': typeof AppImpostazioniNotificheRoute
  '/impostazioni/preferenze': typeof AppImpostazioniPreferenzeRoute
  '/impostazioni/profilo': typeof AppImpostazioniProfiloRoute
  '/impostazioni/scadenze': typeof AppImpostazioniScadenzeRoute
  '/impostazioni/sicurezza': typeof AppImpostazioniSicurezzaRoute
  '/ricette/nuova': typeof AppRicetteNuovaRoute
  '/spesa/storico': typeof AppSpesaStoricoRoute
  '/api/public/hooks/daily-notifications': typeof ApiPublicHooksDailyNotificationsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/dispensa': typeof AppDispensaRouteWithChildren
  '/_app/home': typeof AppHomeRoute
  '/_app/impostazioni': typeof AppImpostazioniRouteWithChildren
  '/_app/piano': typeof AppPianoRoute
  '/_app/ricette': typeof AppRicetteRouteWithChildren
  '/_app/spesa': typeof AppSpesaRouteWithChildren
  '/admin/console': typeof AdminConsoleRoute
  '/admin/log-email': typeof AdminLogEmailRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/utenti': typeof AdminUtentiRoute
  '/join/$code': typeof JoinCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/dispensa/aggiungi': typeof AppDispensaAggiungiRoute
  '/_app/impostazioni/casa': typeof AppImpostazioniCasaRoute
  '/_app/impostazioni/notifiche': typeof AppImpostazioniNotificheRoute
  '/_app/impostazioni/preferenze': typeof AppImpostazioniPreferenzeRoute
  '/_app/impostazioni/profilo': typeof AppImpostazioniProfiloRoute
  '/_app/impostazioni/scadenze': typeof AppImpostazioniScadenzeRoute
  '/_app/impostazioni/sicurezza': typeof AppImpostazioniSicurezzaRoute
  '/_app/ricette/nuova': typeof AppRicetteNuovaRoute
  '/_app/spesa/storico': typeof AppSpesaStoricoRoute
  '/api/public/hooks/daily-notifications': typeof ApiPublicHooksDailyNotificationsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/dispensa'
    | '/home'
    | '/impostazioni'
    | '/piano'
    | '/ricette'
    | '/spesa'
    | '/admin/console'
    | '/admin/log-email'
    | '/admin/logs'
    | '/admin/utenti'
    | '/join/$code'
    | '/admin/'
    | '/dispensa/aggiungi'
    | '/impostazioni/casa'
    | '/impostazioni/notifiche'
    | '/impostazioni/preferenze'
    | '/impostazioni/profilo'
    | '/impostazioni/scadenze'
    | '/impostazioni/sicurezza'
    | '/ricette/nuova'
    | '/spesa/storico'
    | '/api/public/hooks/daily-notifications'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/dispensa'
    | '/home'
    | '/impostazioni'
    | '/piano'
    | '/ricette'
    | '/spesa'
    | '/admin/console'
    | '/admin/log-email'
    | '/admin/logs'
    | '/admin/utenti'
    | '/join/$code'
    | '/admin'
    | '/dispensa/aggiungi'
    | '/impostazioni/casa'
    | '/impostazioni/notifiche'
    | '/impostazioni/preferenze'
    | '/impostazioni/profilo'
    | '/impostazioni/scadenze'
    | '/impostazioni/sicurezza'
    | '/ricette/nuova'
    | '/spesa/storico'
    | '/api/public/hooks/daily-notifications'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/_app/dispensa'
    | '/_app/home'
    | '/_app/impostazioni'
    | '/_app/piano'
    | '/_app/ricette'
    | '/_app/spesa'
    | '/admin/console'
    | '/admin/log-email'
    | '/admin/logs'
    | '/admin/utenti'
    | '/join/$code'
    | '/admin/'
    | '/_app/dispensa/aggiungi'
    | '/_app/impostazioni/casa'
    | '/_app/impostazioni/notifiche'
    | '/_app/impostazioni/preferenze'
    | '/_app/impostazioni/profilo'
    | '/_app/impostazioni/scadenze'
    | '/_app/impostazioni/sicurezza'
    | '/_app/ricette/nuova'
    | '/_app/spesa/storico'
    | '/api/public/hooks/daily-notifications'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  JoinCodeRoute: typeof JoinCodeRoute
  ApiPublicHooksDailyNotificationsRoute: typeof ApiPublicHooksDailyNotificationsRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/utenti': {
      id: '/admin/utenti'
      path: '/utenti'
      fullPath: '/admin/utenti'
      preLoaderRoute: typeof AdminUtentiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/log-email': {
      id: '/admin/log-email'
      path: '/log-email'
      fullPath: '/admin/log-email'
      preLoaderRoute: typeof AdminLogEmailRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/console': {
      id: '/admin/console'
      path: '/console'
      fullPath: '/admin/console'
      preLoaderRoute: typeof AdminConsoleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/spesa': {
      id: '/_app/spesa'
      path: '/spesa'
      fullPath: '/spesa'
      preLoaderRoute: typeof AppSpesaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ricette': {
      id: '/_app/ricette'
      path: '/ricette'
      fullPath: '/ricette'
      preLoaderRoute: typeof AppRicetteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/piano': {
      id: '/_app/piano'
      path: '/piano'
      fullPath: '/piano'
      preLoaderRoute: typeof AppPianoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/impostazioni': {
      id: '/_app/impostazioni'
      path: '/impostazioni'
      fullPath: '/impostazioni'
      preLoaderRoute: typeof AppImpostazioniRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dispensa': {
      id: '/_app/dispensa'
      path: '/dispensa'
      fullPath: '/dispensa'
      preLoaderRoute: typeof AppDispensaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/spesa/storico': {
      id: '/_app/spesa/storico'
      path: '/storico'
      fullPath: '/spesa/storico'
      preLoaderRoute: typeof AppSpesaStoricoRouteImport
      parentRoute: typeof AppSpesaRoute
    }
    '/_app/ricette/nuova': {
      id: '/_app/ricette/nuova'
      path: '/nuova'
      fullPath: '/ricette/nuova'
      preLoaderRoute: typeof AppRicetteNuovaRouteImport
      parentRoute: typeof AppRicetteRoute
    }
    '/_app/impostazioni/sicurezza': {
      id: '/_app/impostazioni/sicurezza'
      path: '/sicurezza'
      fullPath: '/impostazioni/sicurezza'
      preLoaderRoute: typeof AppImpostazioniSicurezzaRouteImport
      parentRoute: typeof AppImpostazioniRoute
    }
    '/_app/impostazioni/scadenze': {
      id: '/_app/impostazioni/scadenze'
      path: '/scadenze'
      fullPath: '/impostazioni/scadenze'
      preLoaderRoute: typeof AppImpostazioniScadenzeRouteImport
      parentRoute: typeof AppImpostazioniRoute
    }
    '/_app/impostazioni/profilo': {
      id: '/_app/impostazioni/profilo'
      path: '/profilo'
      fullPath: '/impostazioni/profilo'
      preLoaderRoute: typeof AppImpostazioniProfiloRouteImport
      parentRoute: typeof AppImpostazioniRoute
    }
    '/_app/impostazioni/preferenze': {
      id: '/_app/impostazioni/preferenze'
      path: '/preferenze'
      fullPath: '/impostazioni/preferenze'
      preLoaderRoute: typeof AppImpostazioniPreferenzeRouteImport
      parentRoute: typeof AppImpostazioniRoute
    }
    '/_app/impostazioni/notifiche': {
      id: '/_app/impostazioni/notifiche'
      path: '/notifiche'
      fullPath: '/impostazioni/notifiche'
      preLoaderRoute: typeof AppImpostazioniNotificheRouteImport
      parentRoute: typeof AppImpostazioniRoute
    }
    '/_app/impostazioni/casa': {
      id: '/_app/impostazioni/casa'
      path: '/casa'
      fullPath: '/impostazioni/casa'
      preLoaderRoute: typeof AppImpostazioniCasaRouteImport
      parentRoute: typeof AppImpostazioniRoute
    }
    '/_app/dispensa/aggiungi': {
      id: '/_app/dispensa/aggiungi'
      path: '/aggiungi'
      fullPath: '/dispensa/aggiungi'
      preLoaderRoute: typeof AppDispensaAggiungiRouteImport
      parentRoute: typeof AppDispensaRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-notifications': {
      id: '/api/public/hooks/daily-notifications'
      path: '/api/public/hooks/daily-notifications'
      fullPath: '/api/public/hooks/daily-notifications'
      preLoaderRoute: typeof ApiPublicHooksDailyNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppDispensaRouteChildren {
  AppDispensaAggiungiRoute: typeof AppDispensaAggiungiRoute
}

const AppDispensaRouteChildren: AppDispensaRouteChildren = {
  AppDispensaAggiungiRoute: AppDispensaAggiungiRoute,
}

const AppDispensaRouteWithChildren = AppDispensaRoute._addFileChildren(
  AppDispensaRouteChildren,
)

interface AppImpostazioniRouteChildren {
  AppImpostazioniCasaRoute: typeof AppImpostazioniCasaRoute
  AppImpostazioniNotificheRoute: typeof AppImpostazioniNotificheRoute
  AppImpostazioniPreferenzeRoute: typeof AppImpostazioniPreferenzeRoute
  AppImpostazioniProfiloRoute: typeof AppImpostazioniProfiloRoute
  AppImpostazioniScadenzeRoute: typeof AppImpostazioniScadenzeRoute
  AppImpostazioniSicurezzaRoute: typeof AppImpostazioniSicurezzaRoute
}

const AppImpostazioniRouteChildren: AppImpostazioniRouteChildren = {
  AppImpostazioniCasaRoute: AppImpostazioniCasaRoute,
  AppImpostazioniNotificheRoute: AppImpostazioniNotificheRoute,
  AppImpostazioniPreferenzeRoute: AppImpostazioniPreferenzeRoute,
  AppImpostazioniProfiloRoute: AppImpostazioniProfiloRoute,
  AppImpostazioniScadenzeRoute: AppImpostazioniScadenzeRoute,
  AppImpostazioniSicurezzaRoute: AppImpostazioniSicurezzaRoute,
}

const AppImpostazioniRouteWithChildren = AppImpostazioniRoute._addFileChildren(
  AppImpostazioniRouteChildren,
)

interface AppRicetteRouteChildren {
  AppRicetteNuovaRoute: typeof AppRicetteNuovaRoute
}

const AppRicetteRouteChildren: AppRicetteRouteChildren = {
  AppRicetteNuovaRoute: AppRicetteNuovaRoute,
}

const AppRicetteRouteWithChildren = AppRicetteRoute._addFileChildren(
  AppRicetteRouteChildren,
)

interface AppSpesaRouteChildren {
  AppSpesaStoricoRoute: typeof AppSpesaStoricoRoute
}

const AppSpesaRouteChildren: AppSpesaRouteChildren = {
  AppSpesaStoricoRoute: AppSpesaStoricoRoute,
}

const AppSpesaRouteWithChildren = AppSpesaRoute._addFileChildren(
  AppSpesaRouteChildren,
)

interface AppRouteChildren {
  AppDispensaRoute: typeof AppDispensaRouteWithChildren
  AppHomeRoute: typeof AppHomeRoute
  AppImpostazioniRoute: typeof AppImpostazioniRouteWithChildren
  AppPianoRoute: typeof AppPianoRoute
  AppRicetteRoute: typeof AppRicetteRouteWithChildren
  AppSpesaRoute: typeof AppSpesaRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDispensaRoute: AppDispensaRouteWithChildren,
  AppHomeRoute: AppHomeRoute,
  AppImpostazioniRoute: AppImpostazioniRouteWithChildren,
  AppPianoRoute: AppPianoRoute,
  AppRicetteRoute: AppRicetteRouteWithChildren,
  AppSpesaRoute: AppSpesaRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminConsoleRoute: typeof AdminConsoleRoute
  AdminLogEmailRoute: typeof AdminLogEmailRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminUtentiRoute: typeof AdminUtentiRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConsoleRoute: AdminConsoleRoute,
  AdminLogEmailRoute: AdminLogEmailRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminUtentiRoute: AdminUtentiRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  JoinCodeRoute: JoinCodeRoute,
  ApiPublicHooksDailyNotificationsRoute: ApiPublicHooksDailyNotificationsRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
