/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSpesaRouteImport } from './routes/_app/spesa'
import { Route as AppRicetteRouteImport } from './routes/_app/ricette'
import { Route as AppPianoRouteImport } from './routes/_app/piano'
import { Route as AppImpostazioniRouteImport } from './routes/_app/impostazioni'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppDispensaRouteImport } from './routes/_app/dispensa'
import { Route as AppRicetteNuovaRouteImport } from './routes/_app/ricette.nuova'
import { Route as AppImpostazioniScadenzeRouteImport } from './routes/_app/impostazioni.scadenze'
import { Route as AppImpostazioniProfiloRouteImport } from './routes/_app/impostazioni.profilo'
import { Route as AppImpostazioniPreferenzeRouteImport } from './routes/_app/impostazioni.preferenze'
import { Route as AppDispensaAggiungiRouteImport } from './routes/_app/dispensa.aggiungi'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSpesaRoute = AppSpesaRouteImport.update({
  id: '/spesa',
  path: '/spesa',
  getParentRoute: () => AppRoute,
} as any)
const AppRicetteRoute = AppRicetteRouteImport.update({
  id: '/ricette',
  path: '/ricette',
  getParentRoute: () => AppRoute,
} as any)
const AppPianoRoute = AppPianoRouteImport.update({
  id: '/piano',
  path: '/piano',
  getParentRoute: () => AppRoute,
} as any)
const AppImpostazioniRoute = AppImpostazioniRouteImport.update({
  id: '/impostazioni',
  path: '/impostazioni',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppDispensaRoute = AppDispensaRouteImport.update({
  id: '/dispensa',
  path: '/dispensa',
  getParentRoute: () => AppRoute,
} as any)
const AppRicetteNuovaRoute = AppRicetteNuovaRouteImport.update({
  id: '/nuova',
  path: '/nuova',
  getParentRoute: () => AppRicetteRoute,
} as any)
const AppImpostazioniScadenzeRoute = AppImpostazioniScadenzeRouteImport.update({
  id: '/scadenze',
  path: '/scadenze',
  getParentRoute: () => AppImpostazioniRoute,
} as any)
const AppImpostazioniProfiloRoute = AppImpostazioniProfiloRouteImport.update({
  id: '/profilo',
  path: '/profilo',
  getParentRoute: () => AppImpostazioniRoute,
} as any)
const AppImpostazioniPreferenzeRoute =
  AppImpostazioniPreferenzeRouteImport.update({
    id: '/preferenze',
    path: '/preferenze',
    getParentRoute: () => AppImpostazioniRoute,
  } as any)
const AppDispensaAggiungiRoute = AppDispensaAggiungiRouteImport.update({
  id: '/aggiungi',
  path: '/aggiungi',
  getParentRoute: () => AppDispensaRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dispensa': typeof AppDispensaRouteWithChildren
  '/home': typeof AppHomeRoute
  '/impostazioni': typeof AppImpostazioniRouteWithChildren
  '/piano': typeof AppPianoRoute
  '/ricette': typeof AppRicetteRouteWithChildren
  '/spesa': typeof AppSpesaRoute
  '/dispensa/aggiungi': typeof AppDispensaAggiungiRoute
  '/impostazioni/preferenze': typeof AppImpostazioniPreferenzeRoute
  '/impostazioni/profilo': typeof AppImpostazioniProfiloRoute
  '/impostazioni/scadenze': typeof AppImpostazioniScadenzeRoute
  '/ricette/nuova': typeof AppRicetteNuovaRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dispensa': typeof AppDispensaRouteWithChildren
  '/home': typeof AppHomeRoute
  '/impostazioni': typeof AppImpostazioniRouteWithChildren
  '/piano': typeof AppPianoRoute
  '/ricette': typeof AppRicetteRouteWithChildren
  '/spesa': typeof AppSpesaRoute
  '/dispensa/aggiungi': typeof AppDispensaAggiungiRoute
  '/impostazioni/preferenze': typeof AppImpostazioniPreferenzeRoute
  '/impostazioni/profilo': typeof AppImpostazioniProfiloRoute
  '/impostazioni/scadenze': typeof AppImpostazioniScadenzeRoute
  '/ricette/nuova': typeof AppRicetteNuovaRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/dispensa': typeof AppDispensaRouteWithChildren
  '/_app/home': typeof AppHomeRoute
  '/_app/impostazioni': typeof AppImpostazioniRouteWithChildren
  '/_app/piano': typeof AppPianoRoute
  '/_app/ricette': typeof AppRicetteRouteWithChildren
  '/_app/spesa': typeof AppSpesaRoute
  '/_app/dispensa/aggiungi': typeof AppDispensaAggiungiRoute
  '/_app/impostazioni/preferenze': typeof AppImpostazioniPreferenzeRoute
  '/_app/impostazioni/profilo': typeof AppImpostazioniProfiloRoute
  '/_app/impostazioni/scadenze': typeof AppImpostazioniScadenzeRoute
  '/_app/ricette/nuova': typeof AppRicetteNuovaRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/dispensa'
    | '/home'
    | '/impostazioni'
    | '/piano'
    | '/ricette'
    | '/spesa'
    | '/dispensa/aggiungi'
    | '/impostazioni/preferenze'
    | '/impostazioni/profilo'
    | '/impostazioni/scadenze'
    | '/ricette/nuova'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/dispensa'
    | '/home'
    | '/impostazioni'
    | '/piano'
    | '/ricette'
    | '/spesa'
    | '/dispensa/aggiungi'
    | '/impostazioni/preferenze'
    | '/impostazioni/profilo'
    | '/impostazioni/scadenze'
    | '/ricette/nuova'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/_app/dispensa'
    | '/_app/home'
    | '/_app/impostazioni'
    | '/_app/piano'
    | '/_app/ricette'
    | '/_app/spesa'
    | '/_app/dispensa/aggiungi'
    | '/_app/impostazioni/preferenze'
    | '/_app/impostazioni/profilo'
    | '/_app/impostazioni/scadenze'
    | '/_app/ricette/nuova'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/spesa': {
      id: '/_app/spesa'
      path: '/spesa'
      fullPath: '/spesa'
      preLoaderRoute: typeof AppSpesaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ricette': {
      id: '/_app/ricette'
      path: '/ricette'
      fullPath: '/ricette'
      preLoaderRoute: typeof AppRicetteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/piano': {
      id: '/_app/piano'
      path: '/piano'
      fullPath: '/piano'
      preLoaderRoute: typeof AppPianoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/impostazioni': {
      id: '/_app/impostazioni'
      path: '/impostazioni'
      fullPath: '/impostazioni'
      preLoaderRoute: typeof AppImpostazioniRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dispensa': {
      id: '/_app/dispensa'
      path: '/dispensa'
      fullPath: '/dispensa'
      preLoaderRoute: typeof AppDispensaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ricette/nuova': {
      id: '/_app/ricette/nuova'
      path: '/nuova'
      fullPath: '/ricette/nuova'
      preLoaderRoute: typeof AppRicetteNuovaRouteImport
      parentRoute: typeof AppRicetteRoute
    }
    '/_app/impostazioni/scadenze': {
      id: '/_app/impostazioni/scadenze'
      path: '/scadenze'
      fullPath: '/impostazioni/scadenze'
      preLoaderRoute: typeof AppImpostazioniScadenzeRouteImport
      parentRoute: typeof AppImpostazioniRoute
    }
    '/_app/impostazioni/profilo': {
      id: '/_app/impostazioni/profilo'
      path: '/profilo'
      fullPath: '/impostazioni/profilo'
      preLoaderRoute: typeof AppImpostazioniProfiloRouteImport
      parentRoute: typeof AppImpostazioniRoute
    }
    '/_app/impostazioni/preferenze': {
      id: '/_app/impostazioni/preferenze'
      path: '/preferenze'
      fullPath: '/impostazioni/preferenze'
      preLoaderRoute: typeof AppImpostazioniPreferenzeRouteImport
      parentRoute: typeof AppImpostazioniRoute
    }
    '/_app/dispensa/aggiungi': {
      id: '/_app/dispensa/aggiungi'
      path: '/aggiungi'
      fullPath: '/dispensa/aggiungi'
      preLoaderRoute: typeof AppDispensaAggiungiRouteImport
      parentRoute: typeof AppDispensaRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppDispensaRouteChildren {
  AppDispensaAggiungiRoute: typeof AppDispensaAggiungiRoute
}

const AppDispensaRouteChildren: AppDispensaRouteChildren = {
  AppDispensaAggiungiRoute: AppDispensaAggiungiRoute,
}

const AppDispensaRouteWithChildren = AppDispensaRoute._addFileChildren(
  AppDispensaRouteChildren,
)

interface AppImpostazioniRouteChildren {
  AppImpostazioniPreferenzeRoute: typeof AppImpostazioniPreferenzeRoute
  AppImpostazioniProfiloRoute: typeof AppImpostazioniProfiloRoute
  AppImpostazioniScadenzeRoute: typeof AppImpostazioniScadenzeRoute
}

const AppImpostazioniRouteChildren: AppImpostazioniRouteChildren = {
  AppImpostazioniPreferenzeRoute: AppImpostazioniPreferenzeRoute,
  AppImpostazioniProfiloRoute: AppImpostazioniProfiloRoute,
  AppImpostazioniScadenzeRoute: AppImpostazioniScadenzeRoute,
}

const AppImpostazioniRouteWithChildren = AppImpostazioniRoute._addFileChildren(
  AppImpostazioniRouteChildren,
)

interface AppRicetteRouteChildren {
  AppRicetteNuovaRoute: typeof AppRicetteNuovaRoute
}

const AppRicetteRouteChildren: AppRicetteRouteChildren = {
  AppRicetteNuovaRoute: AppRicetteNuovaRoute,
}

const AppRicetteRouteWithChildren = AppRicetteRoute._addFileChildren(
  AppRicetteRouteChildren,
)

interface AppRouteChildren {
  AppDispensaRoute: typeof AppDispensaRouteWithChildren
  AppHomeRoute: typeof AppHomeRoute
  AppImpostazioniRoute: typeof AppImpostazioniRouteWithChildren
  AppPianoRoute: typeof AppPianoRoute
  AppRicetteRoute: typeof AppRicetteRouteWithChildren
  AppSpesaRoute: typeof AppSpesaRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDispensaRoute: AppDispensaRouteWithChildren,
  AppHomeRoute: AppHomeRoute,
  AppImpostazioniRoute: AppImpostazioniRouteWithChildren,
  AppPianoRoute: AppPianoRoute,
  AppRicetteRoute: AppRicetteRouteWithChildren,
  AppSpesaRoute: AppSpesaRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
